[global]
developmentMode = false

[server]
runOnSave = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#0a0e1a"
secondaryBackgroundColor = "#1a1d29"
textColor = "#ffffff"
